name: Test Project # Workflow name

on: [push] # Trigger workflow on push

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run test
        run: npm test
