name: Deploy Project

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Get NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: npm test

      - name: Build project # Ensure the "dist" folder is created
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}

    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"

      - name: Get code
        uses: actions/checkout@v4

      - name: Get NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist

      - name: Verify build files exist
        run: ls -l dist || echo "No artifacts found!"

      - name: Publish JS filename
        id: publish
        run: |
          echo "script-file=$(find dist/assets/*.js -type f)" >> $GITHUB_OUTPUT

      - name: Output filename
        run: echo "${{ steps.publish.outputs.script-filee }}"
      - name: Deploy
        run: echo "Deploying..."
